language: c
sudo: required
before_script:
# We want to try perl standalone first
  - sudo apt-get update
  - sudo apt-get install cpanminus nsis
  - sudo cpanm --notest Config::AutoConf::INI ExtUtils::CBuilder File::Basename File::Find File::Path
  - perl CMakeObjects.PL
  - rm -rf output
  - cmake .
script:
  - make check
  - make pack
  - cpack -G NSIS
  - sudo make install
